export const iconsList = [
    'Accessibility', 'Activity', 'AirVent', 'Airplay',
    'AlarmClockOff', 'AlarmClock', 'Album',
    'AlignCenterHorizontal',
    'AlignCenterVertical', 'AlignCenter', 'AlignEndHorizontal',
    'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd',
    'AlignHorizontalDistributeStart', 'AlignHorizontalJustifyCenter',
    'AlignHorizontalJustifyEnd', 'AlignHorizontalJustifyStart',
    'AlignStartVertical', 'AlignVerticalDistributeCenter',
    'AlignVerticalDistributeStart', 'AlignVerticalJustifyCenter',
    'AlignVerticalJustifyEnd', 'AlignVerticalJustifyStart',
    'Antenna', 'Aperture', 'AppWindow', 'Apple', 'ArchiveRestore',
    'AreaChart', 'Armchair', 'ArrowBigDownDash', 'ArrowBigDown',
    'ArrowBigLeftDash', 'ArrowBigLeft', 'ArrowBigRightDash', 'ArrowBigRight',
    'ArrowBigUpDash', 'ArrowBigUp', 'ArrowDown01', 'AlignHorizontalSpaceAround',
    'AlignHorizontalSpaceBetween', 'AlignJustify', 'AlignLeft', 'AlignRight',
    'AlignStartHorizontal', 'AlignVerticalSpaceAround', 'AlignVerticalSpaceBetween',
    'Ampersand', 'Ampersands', 'Anchor', 'Angry', 'Annoyed', 'ArrowDown10',
    'ArrowDownAZ', 'ArrowDownFromLine', 'ArrowDownLeft', 'ArrowDownNarrowWide',
    'ArrowDownRightSquare', 'ArrowDownRight', 'ArrowDownToDot', 'ArrowDownToLine',
    'ArrowDownUp', 'ArrowDownWideNarrow', 'ArrowDownZA', 'ArrowLeftCircle',
    'ArrowLeftFromLine', 'ArrowLeftRight', 'ArrowLeftToLine', 'ArrowLeft',
    'ArrowRightCircle', 'ArrowRightLeft', 'ArrowRightSquare', 'ArrowRightToLine',
    'ArrowUpFromLine', 'ArrowUpLeftFromCircle', 'ArrowUpLeftSquare', 'ArrowUp10',
    'ArrowUpAZ', 'ArrowUpCircle', 'ArrowUpDown', 'ArrowUpNarrowWide', 'ArrowUpRight',
    'ArrowUpSquare', 'ArrowUpToLine', 'ArrowUpWideNarrow', 'ArrowUpZA', 'ArrowsUpFromLine',
    'Asterisk', 'AtSign', 'Atom', 'Award', 'Axe'
];
